[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "drafter"
authors = [{ name = "Austin Cory Bart", email = "acbart@udel.edu" }]
version = "2.0.0"
description = "Student-friendly full stack web development library."
readme = "README.md"
urls = { "github" = "https://github.com/drafter-edu/drafter", "homepage" = "https://drafter-edu.github.io/drafter/" }
license = "MIT"
license-files = ["LICENSE.txt"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Education",

  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",

  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",

  "Topic :: Education",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Software Development :: Libraries :: Application Frameworks",

]
requires-python = ">=3.8"
dependencies = [
  # Server
  "jinja2",
  "watchfiles",
  "websockets>=12",
  "starlette",
  "uvicorn[standard]",
  # CLI Tooling
  "typer",
  "rich",
  # Actual library
  "bakery",
  "pillow",
  "matplotlib",
  # TODO: Is this necessary for compatibility?
  # "typing-extensions; python_version < '3.11'",
]
[dependency-groups]
dev = [
  # Building
  "hatchling",
  # Client Server
  "pyodide-py",
  # New Documentation
  "mkdocs==1.6.1",
  "mkdocs-material",
  "mkdocstrings-python",
  "mkdocs-gen-files",
  "mkdocs-literate-nav",
  "mkdocs-section-index",
  # Future Documentation
  # "zensical",
  # Old Documentation
  "Sphinx",
  "sphinx-rtd-theme",
  "cloud-sptheme",
  "sphinxcontrib-applehelp",
  "sphinxcontrib-devhelp",
  "sphinxcontrib-htmlhelp",
  "sphinxcontrib-jsmath",
  "sphinxcontrib-qthelp",
  "sphinxcontrib-serializinghtml",
  "sphinxcontrib-fulltoc",
  "sphinxjp.themes.basicstrap",
  "sphinxcontrib-mermaid",
  "sphinx-autobuild",
  "sphinx-tabs",
  "Pygments",
  "MarkupSafe",
  # Formatting/Linting
  "djlint",
  "mypy",
  "ruff",
  "mdformat",
  # Tools
  "tqdm",
  "typer",
  # Testing
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "coverage",
  "tox",
  "lxml",
  "html5lib",
]

[project.optional-dependencies]
examples = ["pandas", "seaborn", "requests", "scipy"]

[project.scripts]
drafter = "drafter.cli:main"

[tool.hatch.build]

[tool.hatch.build.targets.sdist]
artifacts = ["js/dist/**"]

[tool.hatch.build.targets.wheel]
packages = ["src/drafter"]

[tool.hatch.build.targets.wheel.force-include]
"js/dist/" = "drafter/assets/"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
mypy_path = ["typings"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
