"""Wrapper around MkDocs CLI that adds optional --dev and --api flags.

When --dev is provided, Drafter's MkDocs plugin compiles embedded demos with
`pyodide_package_style=build` by exporting DRAFTER_MKDOCS_DEV=1 for the mkdocs
process.

When --api is provided, the full API reference is generated by exporting
DRAFTER_MKDOCS_API=1 for the mkdocs process. Without it, tools/gen_ref_pages.py
emits a small placeholder page instead of the per-module mkdocstrings pages,
which makes builds much faster.
"""

from __future__ import annotations

import os
import subprocess
import sys

#: Flags consumed by this wrapper (not forwarded to mkdocs) mapped to the
#: environment variable each one exports for the spawned mkdocs process.
WRAPPER_FLAGS = {
    "--dev": "DRAFTER_MKDOCS_DEV",
    "--api": "DRAFTER_MKDOCS_API",
}


def _strip_wrapper_flags(argv: list[str]) -> tuple[list[str], set[str]]:
    filtered: list[str] = []
    found: set[str] = set()
    for arg in argv:
        if arg in WRAPPER_FLAGS:
            found.add(arg)
            continue
        filtered.append(arg)
    return filtered, found


def main() -> int:
    """Run mkdocs with forwarded arguments, honoring the --dev and --api flags.

    Strips the wrapper-only flags from the command line and, for each one
    present, sets its environment variable to "1" in the environment of the
    spawned mkdocs process.

    Returns:
        Exit code of the mkdocs subprocess.
    """
    forwarded_args, flags = _strip_wrapper_flags(sys.argv[1:])
    env = os.environ.copy()
    for flag in flags:
        env[WRAPPER_FLAGS[flag]] = "1"

    result = subprocess.run(
        [sys.executable, "-m", "properdocs", *forwarded_args],
        env=env,
        check=False,
    )
    return int(result.returncode)


if __name__ == "__main__":
    raise SystemExit(main())
