import * as Diff2Html from "diff2html";
import { Panel } from "./panel";
import type { TestCaseEvent } from "../telemetry/tests";
import type { ReactElement } from "jsx-dom";

export class TestPanel extends Panel {
	private tests: TestCaseEvent[] = [];

	constructor(
		containerId: string,
		instanceId: number,
		root: ParentNode = document,
	) {
		super(
			containerId,
			instanceId,
			"drafter-debug-tests",
			"Your Tests",
			root,
		);
	}

	protected get initialContent() {
		return (
			<>
				<div
					class={`drafter-debug-current-tests-summary drafter-debug-current-tests-summary-${this.instanceId}`}
				></div>
				<br></br>
				<strong>Details: </strong>
				<div
					class={`drafter-debug-current-tests-content-list drafter-debug-current-tests-content-list-${this.instanceId}`}
				></div>
				<div>
					<h4>Regression Tests</h4>
					<div class="drafter-debug-test-actions">
						<div>
							<p>
								Regression tests are used to verify that the
								code you've already written will continue to
								behave the same way in the future. As you
								interact with your website, Drafter
								automatically records the visits and can
								generate <em>Regression Tests</em> based on your
								actions. You can copy the tests to your Python
								code or download them as a .py file to run
								later.
							</p>
							<p>
								Note that Regression tests are not a replacement
								for unit tests, which are written by hand to
								verify specific behaviors of your code.
								Regression tests are there to help you catch
								unexpected changes in behavior as you modify
								your code. They are a good idea when you think
								your website is mostly working. These kinds of
								tests are are sometimes called "brittle" tests
								because they can break easily if you change your
								website's behavior in a way that is actually
								correct. Use them with care.
							</p>
						</div>
						<div>
							<button class="drafter-debug-copy-tests-btn drafter-debug-button--">
								Copy Regression Tests
							</button>
							<button class="drafter-debug-download-tests-btn drafter-debug-button--">
								Download Tests (.py)
							</button>
						</div>
					</div>
				</div>
			</>
		);
	}

	public override initialize() {
		const content = this.getContentElement();
		content
			.querySelector(".drafter-debug-copy-tests-btn")
			?.addEventListener("click", () => {
				void this.copyAllTests();
			});
		content
			.querySelector(".drafter-debug-download-tests-btn")
			?.addEventListener("click", () => this.downloadAllTests());
	}

	/**
	 * Reconstruct a runnable Python source file from every test the
	 * server has reported. Each TestCaseEvent's `caller` is the verbatim
	 * assertion call from the student's code (or generated by the debug
	 * panel), so joining them yields a usable regression-test file.
	 */
	public buildTestSource(): string {
		const lines = [
			"# Tests exported from the Drafter debug panel",
			"from drafter import *",
			"",
		];
		if (this.tests.length === 0) {
			lines.push("# No tests have been run yet.");
		}
		for (const testCase of this.tests) {
			lines.push(
				`# Line ${testCase.line} - ${testCase.passed ? "passed" : "FAILED"}`,
			);
			lines.push(testCase.caller);
			lines.push("");
		}
		return lines.join("\n");
	}

	private async copyAllTests(): Promise<void> {
		const source = this.buildTestSource();
		try {
			await navigator.clipboard.writeText(source);
		} catch {
			// Clipboard API unavailable (e.g. insecure context): fall back
			// to a transient textarea + execCommand copy.
			const scratch = document.createElement("textarea");
			scratch.value = source;
			document.body.appendChild(scratch);
			scratch.select();
			try {
				document.execCommand("copy");
			} finally {
				scratch.remove();
			}
		}
	}

	private downloadAllTests(): void {
		const source = this.buildTestSource();
		const blob = new Blob([source], { type: "text/x-python" });
		const url = URL.createObjectURL(blob);
		const anchor = document.createElement("a");
		anchor.href = url;
		anchor.download = "drafter_tests.py";
		document.body.appendChild(anchor);
		anchor.click();
		anchor.remove();
		URL.revokeObjectURL(url);
	}

	public renderTest(testCase: TestCaseEvent): void {
		this.tests.push(testCase);
		const testList = this.queryWithin(
			this.scopedSelector("drafter-debug-current-tests-content-list"),
			"DebugPanel: Tests section not found.",
		);

		const statusIcon = testCase.passed ? "✅" : "❌";
		const statusClass = testCase.passed ? "test-passed" : "test-failed";

		const testElement = (
			<div class={`test-case ${statusClass}`}>
				<div class="test-case-header">
					<span class="test-status">{statusIcon}</span>
					<span class="test-line">Line {testCase.line}</span>
					<code class="test-caller">{testCase.caller}</code>
				</div>
				{!testCase.passed && testCase.message ? (
					<pre class="test-case-message">{testCase.message}</pre>
				) : null}
				<div class="test-case-diff"></div>
			</div>
		);

		testList.appendChild(testElement);

		this.addDiffToTestElement(testCase, testElement);
	}

	private addDiffToTestElement(
		testCase: TestCaseEvent,
		testElement: ReactElement,
	): void {
		if (!testCase.passed) {
			const diffString = testCase.diff_html;

			console.log(diffString);

			const diffContainer = testElement.querySelector(".test-case-diff");
			if (diffContainer) {
				diffContainer.innerHTML = Diff2Html.html(diffString, {
					drawFileList: false,
					matching: "words",
					diffStyle: "char",
					outputFormat: "side-by-side",
					// outputFormat: "line-by-line",
				});
			} else {
				throw new Error("DebugPanel: Diff container not found.");
			}
		}
	}

	/** Number of failing tests so far (drives the Tests tab badge). */
	public getFailCount(): number {
		return this.tests.filter((t) => !t.passed).length;
	}

	public updateTestSummary(): void {
		const summaryElement = this.queryWithin(
			this.scopedSelector("drafter-debug-current-tests-summary"),
			"DebugPanel: Test summary section not found.",
		);

		const totalTests = this.tests.length;
		const passedTests = this.tests.filter((t) => t.passed).length;
		const failedTests = totalTests - passedTests;

		summaryElement.replaceChildren(
			<div class="test-summary">
				<strong>Summary:</strong>
				<div>Total Tests: {totalTests}</div>
				<div>✅ Passed: {passedTests}</div>
				<div>❌ Failed: {failedTests}</div>
			</div>,
		);
	}
}
