from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class Console(Protocol):
    def log(self, *args: Any) -> None: ...
    def info(self, *args: Any) -> None: ...
    def warn(self, *args: Any) -> None: ...
    def error(self, *args: Any) -> None: ...
    def debug(self, *args: Any) -> None: ...

@runtime_checkable
class Document(Protocol):
    def getElementById(self, id: str) -> Any: ...
    def getElementsByClassName(self, class_name: str) -> Any: ...
    def getElementsByTagName(self, tag_name: str) -> Any: ...
    def createElement(self, tag: str) -> Any: ...
    def createRange(self) -> Any: ...
    def querySelector(self, selector: str) -> Any: ...
    def querySelectorAll(self, selector: str) -> Any: ...
    def addEventListener(
        self, type: str, listener: Any, options: Any = ...
    ) -> None: ...
    def removeEventListener(
        self, type: str, listener: Any, options: Any = ...
    ) -> None: ...

    title: str
    head: Any
    documentElement: Any

    @property
    def body(self) -> Any: ...

@runtime_checkable
class Location(Protocol):
    href: str
    pathname: str
    search: str

@runtime_checkable
class URL:
    def __init__(self, url: str) -> None: ...
    def toString(self) -> str: ...
    @property
    def searchParams(self) -> Any: ...
    @staticmethod
    def new(url: str) -> Any: ...

@runtime_checkable
class History(Protocol):
    def pushState(self, state: Any, title: str, url: str) -> None: ...
    def replaceState(self, state: Any, title: str, url: str) -> None: ...

document: Document
console: Console
location: Location
history: History

class Uint8Array:
    def __init__(self, buffer: Any) -> None: ...
    @staticmethod
    def new(buffer: Any) -> Any: ...
    def __iter__(self) -> Any: ...

class Promise:
    def then(self, on_fulfilled: Any) -> Any: ...
    @staticmethod
    def new(executor: Any) -> Any: ...
    @staticmethod
    def resolve() -> Any: ...

class FormData:
    def __init__(self, form: Any = None, submitter: Any = None) -> None: ...
    def append(self, name: str, value: Any) -> None: ...
    @staticmethod
    def new(form_data: Any, submitter: Any = None) -> Any: ...

def scrollTo(x: int, y: int) -> None: ...

scrollX: int
scrollY: int

# TODO: Provide a better type for DebugPanel
DebugPanel: Any

def addEventListener(
    type: str,
    listener: Any,
    options: Any = ...,
) -> None: ...
def removeEventListener(
    type: str,
    listener: Any,
    options: Any = ...,
) -> None: ...

class CSSStyleSheet:
    def replaceSync(self, css: str) -> None: ...
    @staticmethod
    def new() -> Any: ...
