from dataclasses import dataclass
from drafter.components import (
    PageContent,
    Content,
    Component,
    Div,
    Span,
    LineBreak,
    HorizontalRule,
    Row,
    BulletedList,
    NumberedList,
    List,
    Division,
    Box,
    Text,
    Pre,
    PreformattedText,
    Header,
    TextBox,
    TextArea,
    SelectBox,
    CheckBox,
    Table,
    Link,
    Button,
    Argument,
    Image,
    Download,
    FileUpload,
    MatPlotLibPlot,
)
from drafter.launch import start_server

from drafter.styling.styling import (
    update_style,
    update_attr,
    float_right,
    float_left,
    bold,
    italic,
    underline,
    strikethrough,
    monospace,
    small_font,
    large_font,
    change_color,
    change_background_color,
    change_text_size,
    change_text_font,
    change_text_align,
    change_text_decoration,
    change_height,
    change_width,
    change_border,
    change_margin,
    change_padding,
)
from drafter.client_server.commands import get_main_server, set_main_server
from drafter.router.commands import route
from drafter.payloads.kinds.page import Page
from drafter.payloads.kinds.fragment import Fragment
from drafter.payloads.kinds.update import Update
from drafter.payloads.kinds.redirect import Redirect
from drafter.payloads.kinds.download import Download as DownloadPayload
from drafter.payloads.kinds.progress import Progress
from drafter.deploy import (
    hide_debug_information,
    show_debug_information,
    set_website_title,
    set_website_framed,
    set_website_style,
    add_website_header,
    add_website_css,
    set_site_information,
    get_site_information,
    deploy_site,
)

from drafter.testing import assert_equal

__all__ = [
    "dataclass",
    "Page",
    "Fragment",
    "Update",
    "Redirect",
    "DownloadPayload",
    "Progress",
    "Content",
    "PageContent",
    "Component",
    "get_main_server",
    "set_main_server",
    "route",
    "start_server",
    "PageContent",
    "Div",
    "Span",
    "LineBreak",
    "HorizontalRule",
    "Row",
    "BulletedList",
    "NumberedList",
    "List",
    "Division",
    "Box",
    "Text",
    "Pre",
    "PreformattedText",
    "Header",
    "TextBox",
    "TextArea",
    "CheckBox",
    "SelectBox",
    "Table",
    "Link",
    "Button",
    "Argument",
    "Image",
    "Download",
    "FileUpload",
    "MatPlotLibPlot",
    "hide_debug_information",
    "show_debug_information",
    "set_website_title",
    "set_website_framed",
    "set_website_style",
    "add_website_header",
    "add_website_css",
    "set_site_information",
    "get_site_information",
    "deploy_site",
    "assert_equal",
    "update_style",
    "update_attr",
    "float_right",
    "float_left",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "monospace",
    "small_font",
    "large_font",
    "change_color",
    "change_background_color",
    "change_text_size",
    "change_text_font",
    "change_text_align",
    "change_text_decoration",
    "change_height",
    "change_width",
    "change_border",
    "change_margin",
    "change_padding",
]

__version__ = "2.0.0"

if __name__ == "__main__":
    import sys
    from drafter.command_line import parse_args, build_site

    options = parse_args(sys.argv[1:])
    build_site(options)
