"""Drafter: a friendly web framework for students learning Python.

Drafter turns plain Python functions into interactive websites: routes
(functions decorated with `@route`) take the current state and return a
`Page` of components, and `start_server(state)` launches the site. This
package root re-exports everything a student application needs, so a
single `from drafter import *` provides:

- The `route` decorator, `start_server`, and the `Page`, `Fragment`,
  `Update`, and `Redirect` payload types.
- All page components, from basic content (`Text`, `Header`, `Image`,
  `Table`) and form inputs (`TextBox`, `Button`, `SelectBox`) to richer
  widgets (`Map`, `CurrentLocation`, `Timer`, and the audio family such
  as `Tone`, `Melody`, and `Sound`).
- Data value types for route parameters and state: `Picture` for images,
  `DrafterTextFile`/`DrafterBinaryFile` for uploads, and `Photo` for
  camera captures.
- Styling helpers (`bold`, `change_color`, `update_style`, ...) and site
  configuration functions (`set_website_title`, `set_website_style`, ...).
- Testing and convenience utilities such as `assert_equal`, `dataclass`,
  and `open`.
"""

# Provide dataclass decorator for users' convenience
from dataclasses import dataclass

from drafter.client_server.commands import get_main_server, set_main_server

# Load all the Drafter components
from drafter.components import (
    SVG,
    Abbreviation,
    AddMarkerFunction,
    Argument,
    Article,
    Aside,
    Audio,
    AudioLevel,
    AudioRecorder,
    BlockQuote,
    Box,
    BulletedList,
    Button,
    Camera,
    Canvas,
    CheckBox,
    Clock,
    Component,
    Content,
    CurrentLocation,
    DateInput,
    DateTimeInput,
    DefinitionList,
    DefinitionTerm,
    DeletedText,
    Details,
    Distortion,
    Div,
    Division,
    Download,
    Echo,
    Emphasis,
    Figure,
    FigureCaption,
    FileUpload,
    FooterContent,
    Header,
    HeaderContent,
    HorizontalRule,
    HtmlTag,
    Image,
    InlineCode,
    InlineQuotation,
    InlineVariable,
    InsertedText,
    KeyboardInput,
    Label,
    LineBreak,
    Link,
    Location,
    Main,
    Map,
    MapLocation,
    MapMarker,
    MapView,
    MarkedText,
    MatPlotLibPlot,
    Melody,
    Meter,
    Microphone,
    Muffle,
    Nav,
    NumberedList,
    Output,
    PageContent,
    Paragraph,
    Photo,
    Pre,
    PreformattedText,
    ProgressBar,
    RawHTML,
    Recording,
    RelatedCheckBox,
    RemovePersistent,
    Reverb,
    Row,
    SampleOutput,
    Section,
    SelectBox,
    Sharpen,
    SmallText,
    Sound,
    Span,
    Strong,
    Subscript,
    Superscript,
    Table,
    Text,
    TextArea,
    TextBox,
    TimeInput,
    TimeOutput,
    Timer,
    Tone,
    Video,
)

# Handle configuration if needed
from drafter.configuration import get_system_configuration
from drafter.data.files import DrafterBinaryFile, DrafterTextFile
from drafter.data.images import Picture
from drafter.deploy import (
    add_website_css,
    add_website_header,
    deploy_site,
    get_site_information,
    hide_debug_information,
    set_page_transition,
    set_site_information,
    set_website_favicon,
    set_website_framed,
    set_website_style,
    set_website_title,
    show_debug_information,
)

# Alternative file handling approach
from drafter.files.opening import get_drafter_path, open

# Key starting point for Drafter applications, whether building or running
from drafter.launch import start_server
from drafter.payloads import Fragment, Page, Redirect, Update
from drafter.router.commands import add_route, route
from drafter.styling.generics import update_attr, update_style
from drafter.styling.styling import (
    bold,
    change_background_color,
    change_border,
    change_color,
    change_height,
    change_margin,
    change_padding,
    change_text_align,
    change_text_decoration,
    change_text_font,
    change_text_size,
    change_width,
    float_left,
    float_right,
    italic,
    large_font,
    monospace,
    small_font,
    strikethrough,
    underline,
)
from drafter.testing import (
    assert_attribute,
    assert_children,
    assert_content,
    assert_equal,
    assert_has,
    assert_has_regex,
    assert_in,
    assert_in_regex,
    assert_not_has,
    assert_not_in,
    assert_page,
    assert_state,
    assert_style,
    assert_text,
    set_assertion_defaults,
)
from drafter.version import CURRENT_DRAFTER_VERSION

__all__ = [
    "get_system_configuration",
    "dataclass",
    "open",
    "DrafterTextFile",
    "DrafterBinaryFile",
    "get_drafter_path",
    "Page",
    "Fragment",
    "Update",
    "Redirect",
    "Content",
    "PageContent",
    "Component",
    "get_main_server",
    "set_main_server",
    "route",
    "add_route",
    "start_server",
    "PageContent",
    "Div",
    "Span",
    "LineBreak",
    "HorizontalRule",
    "Row",
    "Paragraph",
    "Section",
    "Article",
    "Aside",
    "Main",
    "Nav",
    "HeaderContent",
    "FooterContent",
    "BulletedList",
    "NumberedList",
    "DefinitionList",
    "Division",
    "Box",
    "Figure",
    "FigureCaption",
    "Details",
    "BlockQuote",
    "Text",
    "InlineCode",
    "HtmlTag",
    "Pre",
    "PreformattedText",
    "Header",
    "Strong",
    "Emphasis",
    "InlineQuotation",
    "DefinitionTerm",
    "Abbreviation",
    "DeletedText",
    "InsertedText",
    "KeyboardInput",
    "MarkedText",
    "SampleOutput",
    "SmallText",
    "Superscript",
    "Subscript",
    "InlineVariable",
    "TextBox",
    "TextArea",
    "CheckBox",
    "RelatedCheckBox",
    "SelectBox",
    "Label",
    "DateTimeInput",
    "DateInput",
    "TimeInput",
    "CurrentLocation",
    "Map",
    "MapLocation",
    "MapMarker",
    "MapView",
    "AddMarkerFunction",
    "Location",
    "ProgressBar",
    "Meter",
    "TimeOutput",
    "Output",
    "RawHTML",
    "Audio",
    "Video",
    "Canvas",
    "SVG",
    "Table",
    "Link",
    "Button",
    "Argument",
    "Image",
    "Picture",
    "Download",
    "FileUpload",
    "MatPlotLibPlot",
    "Timer",
    "Clock",
    "RemovePersistent",
    "Camera",
    "Photo",
    "Tone",
    "Melody",
    "Sound",
    "Microphone",
    "AudioRecorder",
    "AudioLevel",
    "Recording",
    "Echo",
    "Reverb",
    "Muffle",
    "Sharpen",
    "Distortion",
    "hide_debug_information",
    "show_debug_information",
    "set_website_title",
    "set_website_favicon",
    "set_website_framed",
    "set_website_style",
    "set_page_transition",
    "add_website_header",
    "add_website_css",
    "set_site_information",
    "get_site_information",
    "deploy_site",
    "assert_equal",
    "assert_page",
    "assert_state",
    "assert_content",
    "assert_has",
    "assert_in",
    "assert_not_has",
    "assert_not_in",
    "assert_has_regex",
    "assert_in_regex",
    "assert_attribute",
    "assert_style",
    "assert_children",
    "assert_text",
    "set_assertion_defaults",
    "update_style",
    "update_attr",
    "float_right",
    "float_left",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "monospace",
    "small_font",
    "large_font",
    "change_color",
    "change_background_color",
    "change_text_size",
    "change_text_font",
    "change_text_align",
    "change_text_decoration",
    "change_height",
    "change_width",
    "change_border",
    "change_margin",
    "change_padding",
]

__version__ = CURRENT_DRAFTER_VERSION

if __name__ == "__main__":
    # This drafter/__init__.py file was executed directly, unusual circumstance.
    # Give a message to the user about running it normally.
    print(
        "This file is not meant to be executed directly. Please run your Drafter application script instead."
    )
