"""
Demonstration of all ResponsePayload types in Drafter.

This example shows how to use:
- Page: The standard full-page response
- Fragment: A partial HTML snippet
- Update: Update state without changing the page
- Redirect: Navigate to a different route
- Download: Trigger a file download
- Progress: Show progress on long-running tasks
"""
from drafter import *

hide_debug_information()


@dataclass
class State:
    counter: int
    message: str
    mode: str


@route
def index(state: State):
    """Main page showing all available payload types."""
    return Page(
        state,
        [
            Header("Drafter Payload Types Demo"),
            f"Counter: {state.counter}",
            f"Message: {state.message}",
            f"Current Mode: {state.mode}",
            HorizontalRule(),
            Header("Try Different Payload Types:", 2),
            Button("Page (Standard)", use_page),
            Button("Fragment (Partial HTML)", use_fragment),
            Button("Update (State Only)", use_update),
            Button("Redirect", use_redirect),
            Button("Download (File)", use_download),
            Button("Progress (Loading)", use_progress),
        ],
    )


@route
def use_page(state: State):
    """Returns a standard Page payload."""
    state.mode = "Page"
    state.counter += 1
    return Page(
        state,
        [
            Header("Standard Page Payload"),
            "This is a full page response with complete HTML content.",
            f"Counter has been incremented to: {state.counter}",
            Button("Back to Index", index),
        ],
    )


@route
def use_fragment(state: State):
    """Returns a Fragment payload with partial HTML."""
    state.mode = "Fragment"
    html = f"""
    <div style="padding: 20px; background: #e3f2fd; border-radius: 5px;">
        <h3>Fragment Response</h3>
        <p>This is a fragment of HTML injected into the page.</p>
        <p>Fragments are useful for partial page updates.</p>
        <a href="#" data-nav="index">Back to Index</a>
    </div>
    """
    return Fragment(html)


@route
def use_update(state: State):
    """Returns an Update payload that changes state without reloading."""
    state.mode = "Update"
    state.counter += 1
    state.message = f"Updated at counter {state.counter}"
    return Update(state)


@route
def use_redirect(state: State):
    """Returns a Redirect payload that navigates to another route."""
    state.mode = "Redirect"
    state.counter += 1
    # Redirect to the target page with a new Page payload
    return Redirect(
        "redirected_page", Page(state, ["You were redirected here!", Button("Back", index)])
    )


@route
def redirected_page(state: State):
    """The target page for redirects."""
    return Page(
        state,
        [
            Header("Redirected Page"),
            "This page can be reached via redirect.",
            Button("Back to Index", index),
        ],
    )


@route
def use_download(state: State):
    """Returns a Download payload that triggers a file download."""
    state.mode = "Download"
    state.counter += 1
    
    # Create some content to download
    content = f"""
Drafter Download Demo
=====================

Counter value: {state.counter}
Message: {state.message}
Mode: {state.mode}

This file was generated by the Download payload type.
"""
    
    return DownloadPayload(
        file_name="demo.txt",
        content=content,
        mime_type="text/plain"
    )


@route
def use_progress(state: State):
    """Returns a Progress payload showing task progress."""
    state.mode = "Progress"
    state.counter += 1
    
    # Calculate progress based on counter
    progress = min(state.counter * 10, 100)
    
    return Progress(
        message=f"Processing task... (Counter: {state.counter})",
        percent=progress
    )


# Start the server with initial state
start_server(State(counter=0, message="Welcome!", mode="Initial"))
